name: 'Capture Workflow Details'
description: 'Captures workflow details, parameters, and output.'
inputs:
  logging_level:
    description: 'Log level to use: info, debug, error'
    required: true
    default: 'info'
  output_file:
    description: 'Path to store the captured output file'
    required: true
    default: './workflow_output.txt'

runs:
  using: 'node12'
  main: 'index.js'
