name: "Pre/Post Operation"
description: "Collect inputs, timestamps, and save as JSON metadata"
inputs:
  token:
    required: true
    description: GitHub token
  run_id:
    required: true
    description: GitHub run ID
  repository:
    required: true
    description: Repository (owner/repo)
  mode:
    required: true
    description: pre-op or post-op
  job_url:
    required: false
    description: Job URL
  input_json:
    required: false
    description: All workflow inputs as JSON string

outputs:
  metadata:
    description: Combined metadata output

runs:
  using: "composite"
  steps:
    - name: Create metadata folder
      shell: bash
      run: mkdir -p metadata

    - name: Generate Metadata
      shell: bash
      run: |
        MODE="${{ inputs.mode }}"
        JOB_URL="${{ inputs.job_url }}"
        INPUT_JSON='${{ inputs.input_json }}'

        echo "Processing dynamic inputs..."
        DYNAMIC_INPUTS="{"
        first=true
        for key in $(echo "$INPUT_JSON" | jq -r 'keys[]'); do
          value=$(echo "$INPUT_JSON" | jq -r --arg k "$key" '.[$k]')
          if [ "$first" = true ]; then
            first=false
          else
            DYNAMIC_INPUTS+=", "
          fi
          DYNAMIC_INPUTS+="\"$key\": \"$value\""
        done
        DYNAMIC_INPUTS+="}"

        echo "Parsed dynamic inputs: $DYNAMIC_INPUTS"

        if [[ "$MODE" == "pre-op" ]]; then
          START_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          METADATA=$(jq -n \
            --arg start_time "$START_TIME" \
            --arg job_url "$JOB_URL" \
            --argjson inputs "$DYNAMIC_INPUTS" \
            '{phase: "pre-op", start_time: $start_time, job_url: $job_url, inputs: $inputs}')

        elif [[ "$MODE" == "post-op" ]]; then
          END_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          START_TIME=$(jq -r '.start_time' metadata/metadata.json 2>/dev/null || echo "$END_TIME")
          DURATION=$(($(date -d "$END_TIME" +%s) - $(date -d "$START_TIME" +%s)))

          METADATA=$(jq -n \
            --arg start_time "$START_TIME" \
            --arg end_time "$END_TIME" \
            --arg job_url "$JOB_URL" \
            --argjson inputs "$DYNAMIC_INPUTS" \
            --argjson duration "$DURATION" \
            '{phase: "post-op", start_time: $start_time, end_time: $end_time, duration_seconds: $duration, job_url: $job_url, inputs: $inputs}')
        else
          echo "Invalid mode: $MODE"
          exit 1
        fi

        METADATA_SINGLE_LINE=$(echo "$METADATA" | jq -c '.')
        echo "metadata=$METADATA_SINGLE_LINE" >> $GITHUB_OUTPUT
        echo "$METADATA_SINGLE_LINE" > metadata/metadata.json
