name: Trigger Secondary Workflow
description: Collects current job URL and inputs, then triggers another workflow

inputs:
  token:
    description: "PAT with repo and workflow scope"
    required: true
  event_type:
    description: "Event type to trigger in the target workflow"
    required: true
  repository:
    description: "Target repository (owner/repo)"
    required: false
    default: ${{ github.repository }}

runs:
  using: "composite"
  steps:
    - name: Get current job URL
      id: current
      shell: bash
      run: |
        echo "url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_OUTPUT

    - name: Prepare dynamic payload
      id: prepare
      shell: bash
      run: |
        echo "{" > payload.json
        for key in $(jq -r 'keys[]' <<< '${{ toJson(github.event.inputs) }}'); do
          value=$(jq -r --arg k "$key" '.[$k]' <<< '${{ toJson(github.event.inputs) }}')
          echo "  \"$key\": \"$value\"," >> payload.json
        done
        echo "  \"job_url\": \"${{ steps.current.outputs.url }}\"" >> payload.json
        echo "}" >> payload.json
    
    - name: Upload payload as artifact
      uses: actions/upload-artifact@v4
      with:
        name: dynamic-payload
        path: payload.json
    - name: Trigger downstream workflow via curl
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}  # Replace with PAT if triggering another repo
      run: |
        curl -X POST https://api.github.com/repos/DaggupatiPavan/demo124/actions/workflows/workflow-c.yml/dispatches \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{
            "ref": "test"
          }'
    # - name: Trigger downstream workflow
    #   uses: peter-evans/repository-dispatch@v3
    #   with:
    #     token: ${{ inputs.token }}
    #     repository: ${{ inputs.repository }}
    #     event-type: ${{ inputs.event_type }}
    #     client-payload: ${{ steps.prepare.outputs.payload }}
