name: PrePost Operation Workflow

on:
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debug mode"
        required: false
        default: "false"
      environment:
        description: "Environment"
        required: false
        default: "dev"
      region:
        description: "Region"
        required: false
        default: "us-east-1"
      feature_flag:
        description: "Feature flag"
        required: false
        default: "off"

jobs:
  pre_post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pre-Op Step
        uses: ./.github/actions/
        id: preop
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.run_id }}
          repository: ${{ github.repository }}
          mode: pre-op
          job_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          input_json: ${{ toJson(github.event.inputs) }}

      - name: Upload Pre-Op Metadata
        uses: actions/upload-artifact@v4
        with:
          name: pre-op-metadata
          path: metadata/metadata.json

      - name: Main Job Logic
        run: echo "Main work happens here..."

      - name: Post-Op Step
        uses: ./.github/actions/
        id: postop
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ github.run_id }}
          repository: ${{ github.repository }}
          mode: post-op
          job_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          input_json: ${{ toJson(github.event.inputs) }}

      - name: Upload Post-Op Metadata
        uses: actions/upload-artifact@v4
        with:
          name: post-op-metadata
          path: metadata/metadata.json
